apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cicd-demo

  template:
    metadata:
      labels:
        app: cicd-demo

    spec:
      containers:
      - name: cicd-demo
        image: harshalsvaidyaa/cicd-demo:v4
        imagePullPolicy: Always

        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: cicd-demo-config
                key: APP_NAME

          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: cicd-demo-config
                key: ENVIRONMENT

          - name: COMPANY
            valueFrom:
              configMapKeyRef:
                name: cicd-demo-config
                key: COMPANY

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: cicd-demo-secret
                key: DB_USERNAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cicd-demo-secret
                key: DB_PASSWORD

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3